Portfolio/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.render_posts, name='posts'),
    path('<int:post_id>', views.post_detail, name='post_detail'),
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls'))
]

portfolio/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = 'portfolio'

urlpatterns = [
    path('', views.home),
    path('git', views.git, name="git_projects"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models.fields import CharField, TextField
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to = 'blog/images')
    date = models.DateField(datetime.date.today)

    def __str__(self) -> str:
        return self.title

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length = 1000)
    image = ImageField(upload_to='portfolio/images/')
    repository_url = URLField(blank=True)
    deploy_url = URLField(blank=True)

    def __str__(self) -> str:
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {'post': post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all().order_by('title')
    return render(request, 'home.html', {'projects' : projects})
    

def git(request):

    return render(request, 'git.html')

blog/templates/post_detail.html
{% extends "./base.html" %} 
{% block title %}BLOG{%endblock%} 

{% block body %}
<div class="text-center">

<h1> {{post.title}}</h1>
<div class="my-4">
<p> {{post.description|safe}}</p>

</div>
<img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
<div class="my-4">{{post.date}}</div>


</div>

{% endblock %}

blog/templates/posts.html
{% extends "./base.html" %} {% block title %}BLOG{%endblock%} {% block body %}
{% load static %}

<h1 class="fs-2 my-auto py-2">BLOGS</h1>
<h4>
  Exploring Tech Landscapes and Sharing Insights Through My Keyboard Adventures.
</h4>

{% for post in posts %}
<div class="card-blog py-2">
  <a href="{%url 'blog:post_detail' post.id%}" style="text-decoration:none">
    <div class="p-2">
      <div class="card card-body bg-black ">
        <div class="row">
          <div class="col-3">
            <img
              class="img-fluid"
              src="{{post.image.url}}"
              alt="{{post.title}}"
            />
          </div>
          <div class="col-9">
            <h2 class="p-1">{{post.title}}</h2>
            {{post.description|safe|truncatechars:600}}
          </div>
        </div>
      </div>
    </div>
  </a>
</div>

{% endfor %} {% endblock %}

portfolio/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock%}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
  </head>
  <body class="text-light">
    {% include 'partials/navbar.html' %}

    <div class="container p-4">
      {% block body %} {% endblock %}
    </div>

    <footer></footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
  </body>
  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'js/index.js' %}"></script>
</html>

portfolio/templates/git.html
{% extends "base.html" %} {% block title %}GIT PROJECTS {%endblock%} 
{% block body %}
<h1>THESE ARE MY MOST RELEVANT GIT PORTFOLIOS</h1>

<div class="main py-2">

        <!-- Dynamic Appearing repositories-->

</div>
{% endblock %}

portfolio/templates/home.html
{% extends "./base.html" %} {% block title %}HOME{%endblock%} {% block body %}
{% load static %}
<header class="row bg-black">
  <div class="col-md-4">
    <img
      src="{% static 'img/photo.jpg' %}"
      alt="my photo"
      width="308"
      height="365"
    />
  </div>
  <div class="col-md-8 my-auto">
    <h1>I am <stong> Lucas Sanabria</stong></h1>
    <h3>a Backend Developer, QA Automation Engineer and Data Engineer</h3>
    <p>
      I am a seasoned developer with more than two years of expertise.
      Proficient in Python and Django, I've also delved into Java (Spring) and
      PHP (Laravel, Symfony). My prowess extends to SQL databases—PostgreSQL,
      MySQL, and SQL Server. As a QA automation engineer, I orchestrated 100+
      test cases through a robust automation framework. I harnessed pytest BDD,
      selenium, gherkin, and robot for API and UI tests. Well-versed in CI/CD
      pipelines, Docker, and more, I'm a versatile professional dedicated to
      enhancing software quality and delivery. My journey is defined by
      innovation, precision, and a commitment to technological advancement.
    </p>

    <a
      class="btn btn-primary btn-lg rounded-0 my-3"
      href="{% static 'img/Lucas_Sanabria_Resume.pdf'%}"
      target="_blank"
      >Download CV</a
    >
  </div>
</header>

<div class="row my-4 text-center">
  <h3>My Projects</h3>
  <p>
    Crafting Innovative Solutions and Seamless User Experiences Through Code.
  </p>

  {% for project in projects %}
  <div class="col-md-4 p-4">
    <div class="car bg-black card-project">
        <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top" />

      <div class="card-body">
        <h2>{{project.title}}</h2>
        <p>{{ project.description }}</p>
        <a
          href="{{project.repository_url}}"
          class="btn btn-primary"
          target="__blank"
          rel="noreferrer"
          >Visit the repository
          </a>
        {% if project.deploy_url %}
        <div class="p-2"> 
        <a
          href="{{project.deploy_url}}"
          class="btn btn-primary"
          target="__blank"
          rel="noreferrer"
          >Visit the Project</a
        >
      </div>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic" href="/">LsegeCode</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{%url 'blog:posts'%}"
            >Blog</a
          >
        </li>
        <!--
        <li class="nav-item">
          <a class="nav-link" href="{%url 'portfolio:git_projects'%}">Git</a>
        </li>
        -->
        <li class="nav-item d-flex align-items-center">
          <a
            class="btn btn-primary btn-sm"
            href="{% static 'img/Lucas_Sanabria_Resume.pdf'%}"
            target="_blank"
            >Download CV</a
          >
        </li>
      </ul>
    </div>
  </div>
</nav>